### ISSUE TITLE
Hacktoberfest 2020 to 2021 : Changes Should Be Made

### ISSUE THREAD

**Issue by nurulramadhona** [rakshit234/HacktoberFest2021#155]
Sir, I've made some changes to make the website has Hacktoberfest 2021's vibe by changing theme (color), media, and updating links as I mentioned in my pull request #154 

Here you can see:

![Screenshot 2021-10-02 at 07-36-21 Hacktoberfest-2021](https://user-images.githubusercontent.com/29436427/135698457-47af7d4e-5b8a-40cc-8a9f-a0fb5cf58aa6.png)
![Screenshot 2021-10-02 at 07-36-53 Hacktoberfest-2021](https://user-images.githubusercontent.com/29436427/135698459-aadd0aae-9e4e-40d8-8e76-051ecd7114e6.png)
![Screenshot 2021-10-02 at 07-37-10 Hacktoberfest-2021](https://user-images.githubusercontent.com/29436427/135698461-c0bb2c55-5bcb-4b8b-a4d0-cc920a8ef346.png)
![Screenshot 2021-10-02 at 07-37-22 Hacktoberfest-2021](https://user-images.githubusercontent.com/29436427/135698467-8ef228f9-b551-4a40-b845-5aee3e18583c.png)
![Screenshot 2021-10-02 at 07-37-43 Hacktoberfest-2021](https://user-images.githubusercontent.com/29436427/135698469-11cd270a-19da-4486-8fca-cd315b42cfa6.png)
![Screenshot 2021-10-02 at 07-37-52 Hacktoberfest-2021](https://user-images.githubusercontent.com/29436427/135698474-4fbca47f-ce69-4661-9d2c-df96542050f5.png)

**Comment by rakshit234** [comment]
That looks great.

**Comment by nurulramadhona** [comment]
I've worked and made a pull request for this. You've merged it too. Thanks for accepting my work, Sir!

**Comment by nurulramadhona** [comment]
Excuse me, Sir! The pull request I made was marked as an excluded project on me. Then what about my changes?

**Comment by rakshit234** [comment]
@nurulramadhona Make a new PR to the new repository (Hacktoberfest_2021), the link is in the readme.

**Comment by ghost** [comment]
@rakshit234  I made a new PR on the new repo [here](https://github.com/rakshit234/Hacktoberfest_2021/pull/4). Please check it. Thank you.

**Comment by ghost** [comment]
Thank you for merging my PR.
